### ISSUE TITLE
Closing client leads to server error

### ISSUE THREAD

**Issue by mbotsch** [monofon/quizzer#3]
1. Start a polling session
2. Open a polling client, (optionally submit a vote
3. Stop the polling
4. Close the client (after the session has been closed)

This throws an error, since `session.ui.onFinished()` is called (poll.js, line 132) but the `session.ui` has been set to `null` before (in step 3 above).

Closing a client for a closed session should probably not trigger anything.

**Comment by monofon** [comment]
This is not happening here.

**Comment by mbotsch** [comment]
Still happening...

https://github.com/decker-edu/quizzer/assets/31275467/1bb575e4-0107-48ac-a12a-ac1066ea76a2
