### ISSUE TITLE
manually re-connecting to server fails

### ISSUE THREAD

**Issue by mbotsch** [monofon/quizzer#4]
1. Start polling session
2. Start and connect client
3. Stop and restart server (maybe triggered by an error)
4. Client presses re-load, then enters 4-digit ID, but nothing happens

The event listener in line 154 of `quizzer.html` should also be added if pollId (the hash value) exists. Otherwise, if the pollID is wrong and the call to connect() fails (and then the callbacks for "error" and "close" are called), we call `input.focus()`, but the keyup handler is not installed. Consequently, pollid() is never called and you cannot connect by entering an ID.

**Comment by monofon** [comment]
Cannot reproduce that.

**Comment by monofon** [comment]
The `keyup` handler is always installed.

**Comment by mbotsch** [comment]
This is why you couldn't reproduce it: c11f626cb3ec43b12cf820fc4d7e99e83a6155c1
