### ISSUE TITLE
number of possible votes not respected

### ISSUE THREAD

**Issue by mbotsch** [monofon/quizzer#5]
When starting a new poll, the client passes as "votes" the number of possible votes (i.e., the number of correct answers). In branch random-winner this number seems to be ignored.

I don't get the Haskell part, but when a client connects to the server, any message sent to the client should contain in message.votes the number of correct answers. Previously this number was correct. In the new branch this number is 0. 

As a consequence, buttons do not get disabled when enough answers are given. Can be reproduced with the simple presenter.html, which should allow for two answers, but nvotes==0 and >2 answers can be given.

**Comment by monofon** [comment]
No further complaints. Seems to work.
